# Generated by Django 2.1.3 on 2018-11-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswerSituation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.IntegerField(verbose_name='试卷编号')),
                ('uid', models.IntegerField(verbose_name='用户编号')),
                ('correct_choice_problem_amount', models.IntegerField(default=0, verbose_name='用户答对的选择题数')),
                ('correct_judge_problem_amount', models.IntegerField(default=0, verbose_name='用户答对的判断题数')),
                ('fill_blank_problem_scores', models.FloatField(default=0, verbose_name='用户填空题总得分')),
                ('QA_problem_scores', models.FloatField(default=0, verbose_name='用户问答题总得分')),
                ('operate_problem_scores', models.FloatField(default=0, verbose_name='用户操作题总得分')),
                ('last_updated_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name_plural': '用户答题与得分情况',
                'db_table': 'User_Answer_Situation',
                'ordering': ['last_updated_time'],
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='each_choice_problem_score',
            field=models.FloatField(default=0, verbose_name='每道选择题分数'),
        ),
        migrations.AddField(
            model_name='paper',
            name='each_judge_problem_score',
            field=models.FloatField(default=0, verbose_name='每道判断题分数'),
        ),
    ]
