# Generated by Django 2.1.3 on 2018-11-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0002_auto_20181107_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceproblem',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否被删除'),
        ),
        migrations.AlterField(
            model_name='fillblankproblem',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否被删除'),
        ),
        migrations.AlterField(
            model_name='judgeproblem',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否被删除'),
        ),
        migrations.AlterField(
            model_name='operateproblem',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否被删除'),
        ),
        migrations.AlterField(
            model_name='qaproblem',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否被删除'),
        ),
    ]
