# Generated by Django 2.1.3 on 2018-12-09 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0002_auto_20181209_1222'),
    ]

    operations = [
    ]
