# Generated by Django 2.1.3 on 2018-12-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0002_auto_20181122_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operateproblem',
            name='content',
            field=models.TextField(verbose_name='题目内容'),
        ),
        migrations.AlterField(
            model_name='qaproblem',
            name='content',
            field=models.TextField(verbose_name='题目内容'),
        ),
    ]
