# Generated by Django 2.1.3 on 2018-12-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0003_auto_20181209_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchoiceanswer',
            name='scores',
        ),
        migrations.RemoveField(
            model_name='userjudgeanswer',
            name='scores',
        ),
        migrations.AddField(
            model_name='userchoiceanswer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='回答是否正确'),
        ),
        migrations.AddField(
            model_name='userjudgeanswer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='回答是否正确'),
        ),
    ]
