# Generated by Django 2.1.3 on 2018-11-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0003_auto_20181107_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paper_id', models.AutoField(primary_key=True, serialize=False, verbose_name='试卷编号')),
                ('level', models.IntegerField(verbose_name='难度系数')),
                ('paper_name', models.CharField(max_length=50, verbose_name='试卷名称')),
                ('tag', models.CharField(blank=True, max_length=50, null=True, verbose_name='试卷标签')),
                ('author', models.CharField(blank=True, max_length=50, null=True, verbose_name='作者')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否被删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '试卷',
                'db_table': 'Paper',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='PaperProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.IntegerField(verbose_name='试卷编号')),
                ('problem_type', models.CharField(max_length=20, verbose_name='题目类型')),
                ('problem_id', models.IntegerField(verbose_name='题目编号')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否被删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '试卷与试题关系',
                'db_table': 'Paper_Problem',
                'ordering': ['paper_id'],
            },
        ),
        migrations.CreateModel(
            name='PaperUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.IntegerField(verbose_name='试卷编号')),
                ('uid', models.IntegerField(verbose_name='用户编号')),
                ('is_owner', models.BooleanField(default=False, verbose_name='是否拥有修改权')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否被删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '试卷与用户关系',
                'db_table': 'Paper_User',
                'ordering': ['paper_id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField(verbose_name='老师编号')),
                ('student_id', models.IntegerField(verbose_name='学生编号')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否被删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '老师与学生关系',
                'db_table': 'Tea_Stu',
                'ordering': ['teacher_id'],
            },
        ),
    ]
