# Generated by Django 2.1.3 on 2018-12-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0005_auto_20181208_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiceproblem',
            name='problem_type',
            field=models.CharField(default='选择题', max_length=50, verbose_name='题目类型'),
        ),
        migrations.AddField(
            model_name='fillblankproblem',
            name='problem_type',
            field=models.CharField(default='填空题', max_length=50, verbose_name='题目类型'),
        ),
        migrations.AddField(
            model_name='judgeproblem',
            name='problem_type',
            field=models.CharField(default='判断题', max_length=50, verbose_name='题目类型'),
        ),
        migrations.AddField(
            model_name='operateproblem',
            name='problem_type',
            field=models.CharField(default='实际操作题', max_length=50, verbose_name='题目类型'),
        ),
        migrations.AddField(
            model_name='qaproblem',
            name='problem_type',
            field=models.CharField(default='问答题', max_length=50, verbose_name='题目类型'),
        ),
    ]
