# Generated by Django 2.1.3 on 2018-12-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0006_auto_20181208_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceproblem',
            name='level',
            field=models.IntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难')], default=1, verbose_name='难度系数'),
        ),
        migrations.AlterField(
            model_name='fillblankproblem',
            name='level',
            field=models.IntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难')], default=1, verbose_name='难度系数'),
        ),
        migrations.AlterField(
            model_name='judgeproblem',
            name='level',
            field=models.IntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难')], default=1, verbose_name='难度系数'),
        ),
        migrations.AlterField(
            model_name='operateproblem',
            name='level',
            field=models.IntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难')], default=1, verbose_name='难度系数'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='level',
            field=models.IntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难')], default=1, verbose_name='难度系数'),
        ),
        migrations.AlterField(
            model_name='qaproblem',
            name='level',
            field=models.IntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难')], default=1, verbose_name='难度系数'),
        ),
    ]
