# Generated by Django 2.1.3 on 2018-12-08 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0007_auto_20181208_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperuser',
            name='is_owner',
        ),
        migrations.AddField(
            model_name='paper',
            name='owner_id',
            field=models.IntegerField(default=0, verbose_name='试卷管理员id'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2099, 1, 1, 0, 0), verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='开始时间'),
        ),
    ]
